'use strict';
function renderBrief(){G.Profile.ensure(state);const C=G.Career,c=state.career,r=C.current(state),p=state.profile,last=state.reviews.at(-1),tenure=state.month-c.since,year=Math.floor(state.month/12)+1,age=c.ageAtStart+Math.floor(state.month/12),score=last?.score??Math.round((state.happiness+state.reputation)/2),careerProgress=Math.min(100,state.month/C.LIMIT*100);
 const agenda=state.agenda&&G.AGENDAS[state.agenda.id],tasks=[agenda?`年度重点：${agenda.name}`:(state.events.length?`${state.events.length} 件治理事件待处理`:'当前没有逾期事件'),c.application?`${C.byId(c.application.target).title}任用程序办理中`:'可在任职页查看岗位窗口',p.health<60?'健康状态需要优先安排':'健康状态适合正常履职'];
 $('briefview').innerHTML=`<div class="brief-shell"><section class="brief-identity"><div class="brief-kicker">第 ${year} 年工作简报</div><div class="brief-title"><div><strong>${age} 岁</strong><h2>${escape(r.title)}</h2></div><span>${escape(C.GRADES[r.grade])}</span></div><div class="brief-facts"><span>职务类型　${r.branch==='party'?'党委岗位':'政府岗位'}</span><span>治理层级　${C.TIERS[r.tier]}</span><span>工作范围　${escape(C.roleScope(r))}</span><span>居住　${p.housing}</span><span>交通　${p.transport}</span></div><div class="brief-progress"><div><span>履历进度　${state.month} / ${C.LIMIT} 月</span><span>本职任期 ${tenure} 月</span></div><i><b style="width:${careerProgress}%"></b></i></div><div class="personal-money"><span><small>个人存款</small><strong>${fmt(p.cash)} 万</strong></span><span><small>住房公积金</small><strong>${fmt(p.housingFund)} 万</strong></span><span><small>养老账户</small><strong>${fmt(p.pension)} 万</strong></span><span><small>本年模拟收入</small><strong>${fmt(p.yearIncome)} 万</strong></span></div><p class="brief-note">个人账户按游戏参数结算，与政府可用财政、项目资金和公共预算完全分开。</p></section>
 <section class="brief-metrics"><article><small>最近年度考核</small><strong>${last?fmt(last.score):'—'}</strong><span>${last?last.grade:'尚未归档'}</span></article><article><small>累计履职月份</small><strong>${state.month}</strong><span>${c.records.length} 段任职记录</span></article><article><small>责任记录</small><strong>${state.risks.length}</strong><span>${state.risks.length?'任用时持续核查':'当前清白履职'}</span></article><article><small>健康状态</small><strong>${fmt(p.health)}</strong><span>${p.health>=75?'状态良好':p.health>=50?'需要关注':'建议立即管理'}</span></article></section>
 <section class="brief-work"><div><h2>本月工作提醒</h2>${tasks.map((x,i)=>`<p><b>0${i+1}</b>${escape(x)}</p>`).join('')}</div><button data-brief="govern" class="brief-primary">返回治理现场</button></section>
 <section class="brief-actions"><div class="brief-section-title"><h2>个人事项</h2><span>选择事项可直接办理或打开对应台账</span></div><div class="brief-action-list"><button data-brief="career"><b>01</b><span><strong>查看晋升路径</strong><small>岗位条件、任用程序与完整履历</small></span><em>打开 →</em></button><button data-brief="care" ${state.ended||state.month-p.lastCare<3?'disabled':''}><b>02</b><span><strong>健康管理</strong><small>个人支出 0.35 万，恢复 9 点；每季度一次</small></span><em>${state.month-p.lastCare<3?'本季已安排':'办理 →'}</em></button><button data-brief="house" ${p.housing==='自有住房'||p.cash<18?'disabled':''}><b>03</b><span><strong>购置住房</strong><small>个人支出 18 万；改善长期居住安排</small></span><em>${p.housing==='自有住房'?'已购置':'办理 →'}</em></button><button data-brief="car" ${p.transport==='自有车辆'||p.cash<5?'disabled':''}><b>04</b><span><strong>购置车辆</strong><small>个人支出 5 万，之后计入月度养护</small></span><em>${p.transport==='自有车辆'?'已购置':'办理 →'}</em></button><button data-brief="fund"><b>05</b><span><strong>住房公积金账户</strong><small>查看最近缴存与个人生活支出</small></span><em>查看 →</em></button><button data-brief="pension"><b>06</b><span><strong>养老账户</strong><small>查看模拟缴存记录</small></span><em>查看 →</em></button></div></section><p class="brief-disclaimer">收入、缴存、住房与车辆价格均为游戏平衡参数，不代表现实地区标准或政策待遇。</p></div>`;
 $('briefview').querySelector('.brief-actions').insertAdjacentHTML('beforeend',lifePanel());
 document.body.classList.toggle('brief-mode',worldView==='brief');
}
function briefLedger(kind){const p=state.profile,isFund=kind==='fund',title=isFund?'住房公积金账户':'养老账户',key=isFund?'fund':'pension';show(`<h2>${title}</h2>${row('当前余额',fmt(p[isFund?'housingFund':'pension'])+' 万元')}<p class="muted">每月按模拟收入的 8% 记入个人账户，仅用于展示职业生涯的长期积累。</p><h3>最近缴存</h3>${p.ledger.length?p.ledger.slice(0,12).map(x=>row('履职第 '+x.month+' 月',fmt(x[key])+' 万')).join(''):'<p class="muted">推进一个月后产生首笔记录。</p>'}`);}
function handleBrief(e){const life=e.target.closest('[data-life]');if(life){const err=G.Profile.life(state,life.dataset.life);act(err);if(!err)toast('已办理：'+life.dataset.life);return;}if(e.target.closest('[data-life-next]')){advance(1);return;}if(e.target.closest('[data-life-record]')){show('<h2>个人收支明细</h2>'+state.profile.ledger.map(x=>row('第'+x.month+'月','收入 '+fmt(x.pay)+' · 生活与房贷 '+fmt(x.living)+' 万')).join(''));return;}const b=e.target.closest('[data-brief]');if(!b)return;const a=b.dataset.brief;if(a==='career'){tab='career';worldView=state.level>0?'region':'map';render();return;}if(a==='govern'){worldView=state.level>0?'region':'map';render();return;}if(a==='fund'||a==='pension'){briefLedger(a);return;}if(a==='care')act(G.personalCare(state));if(a==='house')act(G.buyHouse(state));if(a==='car')act(G.buyCar(state));}

function lifePanel(){const p=state.profile;return `<h3>生活与家庭</h3><p>${p.family} · 关系 ${fmt(p.relationship)}/100 · 子女 ${p.children} 人 · 节奏 ${p.pace}</p><p>房贷余额 ${fmt(p.mortgage)} 万 · 生活欠款 ${fmt(p.personalDebt)} 万</p><p class="brief-note">进取：每月声誉 +0.12，健康额外 −0.8；休养：每月健康额外 +1.1、支出 +0.12 万。家庭增加生活费用，进取时相处关系会下降。</p><div class="actions">${['均衡','进取','休养'].map(x=>`<button data-life="${x}" ${state.ended?'disabled':''}>${x}</button>`).join('')}</div><div class="brief-action-list">${[['认识伴侣','支出 0.15 万，开始恋爱'],['相处陪伴','支出 0.12 万，关系 +15'],['登记结婚','关系需 65，支出 1.5 万'],['养育子女','已婚、关系需60；支出0.8万，月生活费增加0.12万'],['按揭购房','首付6万，借款12万；月息0.3%，每月计划偿还本金0.1万'],['提前还款','先偿生活欠款，再偿房贷；最多2万']].map(([a,d])=>`<button data-life="${a}" ${state.ended?'disabled':''}><b>·</b><span><strong>${a}</strong><small>${d}</small></span><em>办理 →</em></button>`).join('')}</div><p class="brief-note">生活事项每月一次；贷款和节奏调整独立办理。资金不足产生个人欠款，后续可主动偿还。</p><h3>个人年度账本</h3>${p.annual.length?p.annual.slice().reverse().map(x=>`<p>第${x.year}年 · 收入${fmt(x.income)}万 · 支出${fmt(x.expense)}万 · 年末存款${fmt(x.cash)}万 · 健康${fmt(x.health)}</p>`).join(''):'<p>每12个月归档一次。从本次升级后开始累计。</p>'}<div class="actions"><button data-life-next="1">推进下月 →</button><button data-life-record="1">个人收支明细</button></div>`;}
