function budgetFmt(n){return n>=10000?fmt(n/10000)+' 亿元':fmt(n)+' 万元';}
// 与 app.js 共用渲染工具；所有内容均来自本地规则与已校验的存档。
function careerPanel(){const C=G.Career,c=state.career,r=C.current(state),tenure=state.month-c.since;
 let html='<h2>任职与组织考察</h2><p class="muted">条件审查、考察、相应任用程序与交接。</p>'+row('现任职务',r.title)+row('职务层次',C.GRADES[r.grade])+row('本职任职',tenure+' 个月')+row('累计模拟履职',state.month+' / '+C.LIMIT+' 个月')+row('近两年考核均分',fmt(C.recentScore(state)))+row('同级交流记录',c.records.filter(x=>x.reason.includes('交流')).length+' 次');
 if(c.role==='town'&&!c.application)html+='<div class="notice"><strong>镇长晋升提示</strong><br>先完成 12 个月任职并形成 1 份年度考核，满足合格分数与声誉条件后，可申请同级岗位“镇党委书记”；在岗继续治理、处理事件和改善公共服务，会让下一步副县长条件逐渐具备。</div>';
 if(c.mode==='scenario')html+='<div class="notice">分层体验开局：初始岗位由你指定，不代表从基层获得任用。之后仍按同样规则推进。</div>';
 if(c.application){const a=c.application,steps=C.procedures(C.byId(a.target));html+=`<h3>办理中 · ${C.byId(a.target).title}</h3><ol class="steps">${steps.map((x,i)=>`<li class="${i===a.stage?'current':''}">${i<a.stage?'已完成 · ':i===a.stage?'当前 · ':''}${x}</li>`).join('')}</ol><p class="muted">下个月反馈。每个阶段重新核查财政、声誉和责任记录。</p>`;}
 html+='<h3>可选任职路径</h3>';
 const ops=C.opportunities(state);html+=ops.length?ops.map(({role:t,reasons})=>`<article class="job"><strong>${t.title}</strong><span class="muted">${C.TIERS[t.tier]} · ${C.GRADES[t.grade]} · ${t.grade===r.grade?'交流任职':'上一级岗位'}</span><p class="muted">${reasons.length?escape(reasons.join('；')):'游戏条件已满足，当前岗位窗口开放。'}</p><button data-role="${t.id}" ${reasons.length?'disabled':''}>进入人选考察</button></article>`).join(''):'<div class="notice">已到达当前路径最高岗位。继续履职、处理治理事项并完成阶段报告。</div>';
 html+='<p class="muted">任职等待、均分、声誉及空缺窗口为游戏参数。现实任用不是积分兑换，也不保证沿此路径晋升。</p><div class="actions"><button data-career="train" '+(state.ended?'disabled':'')+'>专题研修</button><button data-career="rotate" '+(state.ended?'disabled':'')+'>同级交流 / 分工轮换</button></div>';
 if(c.trainingUntil>state.month)html+='<p class="muted">研修还需 '+(c.trainingUntil-state.month)+' 个月。</p>';else if(c.trainedUntil>state.month)html+='<p class="good">研修执行加成还剩 '+(c.trainedUntil-state.month)+' 个月。</p>';
 html+='<h3>任职履历</h3>'+[...c.records].reverse().map(x=>`<div class="log"><strong>${C.byId(x.role).title}</strong><small>第 ${x.start} 月 — ${x.end===null?'至今':'第 '+x.end+' 月'} · ${escape(x.reason)}</small></div>`).join('');
 html+='<h3>年度考核</h3>'+(state.reviews.length?[...state.reviews].reverse().map(x=>row('第 '+x.year+' 年',escape(x.grade)+' · '+fmt(x.score))).join(''):'<p class="muted">每 12 个月出具年度报告。</p>');
 html+='<h3>五年报告</h3>'+(c.terms.length?c.terms.map(x=>row('第 '+x.month/12+' 年',C.byId(x.role).title+' · '+fmt(x.score)+' 分')).join(''):'<p class="muted">五年只是阶段节点，不再结束整局。</p>');
 html+='<h3>责任档案</h3>'+(state.risks.length?state.risks.map(x=>`<div class="log">${escape(x.title)}<small>第 ${x.month} 月记录；${state.month-x.month<60?'仍在任职核查观察期':'历史责任继续留存'}</small></div>`).join(''):'<p class="good">暂无责任记录。</p>');return html;
}
function renderRegional(){const C=G.Career,r=C.current(state),w=C.world(state);$('viewRegion').disabled=r.tier===0;$('mapview').hidden=worldView!=='map';$('regional').hidden=worldView!=='region';$('systemview').hidden=worldView!=='system';$('briefview').hidden=worldView!=='brief';
 for(const [id,v] of [['viewBrief','brief'],['viewMap','map'],['viewRegion','region'],['viewSystem','system']]){$(id).classList.toggle('active',worldView===v);$(id).setAttribute('aria-pressed',String(worldView===v));}
 $('regional').innerHTML=`<div class="regionhead"><h2>${C.roleScope(r)} · ${r.branch==='party'?'统筹与督察':'区域治理'}</h2><p>${r.title} · ${r.deputy?'当前分管 '+w.regions[state.career.assignment].name:'统筹本级辖区'}。提案经过集体讨论与执行反馈后生效。</p><p class="muted">本级预算与基层样本分账。地区为虚构样本，不对应真实全国统计。</p></div><div class="regional-money">${row('本级可用资金',budgetFmt(w.cash))+row('年度工作预算',budgetFmt(w.spent)+' / '+budgetFmt(w.limit))+row('上月本级结余',budgetFmt(w.monthlyIncome-w.monthlyExpense))}</div><div class="regions">${w.regions.map(x=>`<article class="region"><div class="regiontitle"><h3>${escape(x.name)}</h3><span>${fmt(x.pop/10000)} 万人</span></div>${[['education','教育'],['health','医疗'],['employment','就业'],['environment','环境'],['capacity','执行能力']].map(([k,n])=>meter(n,x[k])).join('')}<div class="regionactions">${Object.entries(C.DOMAINS).map(([k,d])=>{let locked=state.ended||(r.deputy&&x.id!==w.regions[state.career.assignment].id)||(r.branch==='party'&&!['audit','education','ecology'].includes(k));return `<button data-region="${x.id}" data-domain="${k}" ${locked?'disabled':''}>${d.name}<small>${budgetFmt(d.cost*w.scale)}</small></button>`;}).join('')}</div></article>`).join('')}</div><p class="muted">上级提案完成后每隔两个月向下一级传导协同效果；各级预算独立，指标传导不等同资金拨付。</p><h3>办理中的议题</h3>${w.motions.length?w.motions.map(x=>row(escape(w.regions.find(r=>r.id===x.region).name)+' · '+C.DOMAINS[x.kind].name,(x.due-state.month)+' 月后反馈')).join(''):'<p class="muted">暂无议题。优先改善短板，同时留意新增运维成本。</p>'}`;
 $('systemview').innerHTML=`<h2>中央到地方 · 机构与岗位</h2><p class="muted">五级治理主干与机构职责。市级并非所有地区必经层级，乡镇不设人大常委会；本版展示常见地方主干。</p><div class="hierarchy">${[4,3,2,1,0].map(t=>`<section class="tier ${t===r.tier?'selected-tier':''}"><strong>${C.TIERS[t]}</strong><div>${C.ROLES.filter(x=>x.tier===t).map(x=>`<span class="rolechip ${x.id===r.id?'current-role':''}">${x.title}${x.id===r.id?' · 现任':''}</span>`).join('')}</div></section>`).join('')}</div><h3>机构分工</h3><div class="institutions">${C.INSTITUTIONS.map(x=>`<article><h3>${x.name}</h3><small>${x.scope}</small><p>${x.text}</p></article>`).join('')}</div><p class="muted">党政主要岗位可玩；人大、政协、国家主席、纪检监察、司法与军队在本版为权责参照，未做各自独立职业路线。职务层次按常见主干简化，不覆盖兼任与高配情形。</p>`;
}
function scenarioDialog(){show('<h2>选择职业开局</h2><p>基层职业从镇长开始，最长 35 年。也可指定岗位体验不同层级，分层开局会明确记录在履历中。</p><label class="field">开局方式<select id="newmode"><option value="career">基层职业 · 镇长起步</option><option value="scenario">分层体验 · 指定岗位</option></select></label><label class="field">体验岗位<select id="newrole" disabled>'+G.Career.ROLES.map(r=>`<option value="${r.id}" ${r.id==='town'?'selected':''}>${G.Career.TIERS[r.tier]} · ${r.title}</option>`).join('')+'</select></label><p class="muted">将替换当前浏览器存档。可先导出备份。</p><div class="actions"><button id="modalexport">备份当前存档</button><button id="confirmcareer" class="primary">确认开始</button></div>');$('newmode').onchange=()=>{$('newrole').disabled=$('newmode').value==='career';};$('confirmcareer').onclick=()=>{state=G.initial($('newmode').value==='career'?'town':$('newrole').value,$('newmode').value);tool='inspect';tab='career';selected=null;worldView=state.level>0?'region':'map';$('dialog').close();persist();render();};}
