const {test}=require('node:test'),assert=require('node:assert/strict'),G=require('./engine'),C=G.Career;
function eligible(role='town'){const s=G.initial(role);s.month=48;s.career.since=0;s.reputation=90;s.reviews=[{year:3,score:85,grade:'优秀'},{year:4,score:85,grade:'优秀'}];return s;}
function findWindow(s,id){while(C.requirements(s,id).some(x=>x.includes('空缺')))s.month++;}
test('所有19个岗位均可开局、结算和保存',()=>{assert.equal(C.ROLES.length,19);for(const r of C.ROLES){let s=G.initial(r.id,'scenario');assert.equal(s.level,r.tier);G.next(s);G.validate(JSON.parse(JSON.stringify(s)));}});
test('政府主线正副职逐级连接，可达中央总理',()=>{let path=['town','viceCounty','county','viceCity','city','viceProvince','province','vicePremier','premier'];for(let i=0;i<path.length-1;i++){assert.ok(C.PATHS[path[i]].includes(path[i+1]));assert.equal(C.byId(path[i+1]).grade-C.byId(path[i]).grade,1);}});
test('党委与部委分支具有中央终点，常委资格前置',()=>{assert.ok(C.PATHS.provinceParty.includes('secretariat'));assert.ok(C.PATHS.secretariat.includes('standing'));assert.ok(C.PATHS.standing.includes('generalSecretary'));assert.ok(!C.PATHS.secretariat.includes('generalSecretary'));assert.ok(C.PATHS.city.includes('viceMinister'));});
test('年限和考核不满足不会自动升职',()=>{let s=G.initial();assert.ok(G.applyRole(s,'viceCounty'));for(let i=0;i<36;i++){G.next(s);for(const e of [...s.events])G.resolve(s,e.id,1);}assert.equal(s.career.role,'town');});
test('镇长完成一年合格履职后可以申请同级镇党委书记',()=>{let s=G.initial();for(let i=0;i<12;i++)G.next(s);assert.deepEqual(C.opportunities(s).find(x=>x.role.id==='townParty').reasons,[]);assert.equal(G.applyRole(s,'townParty'),null);for(let i=0;i<3;i++)G.next(s);assert.equal(s.career.role,'townParty');});
test('满足条件仍需三阶段任职，交接保留旧债',()=>{let s=eligible();findWindow(s,'viceCounty');s.debt=120;assert.equal(G.applyRole(s,'viceCounty'),null);G.next(s);assert.equal(s.career.role,'town');assert.equal(s.career.application.stage,1);G.next(s);assert.equal(s.career.role,'town');G.next(s);assert.equal(s.career.role,'viceCounty');assert.equal(s.level,1);assert.equal(s.debt,120);assert.equal(s.career.records[0].end,s.month);G.validate(JSON.parse(JSON.stringify(s)));});
test('核查期间出现责任记录将中止任职',()=>{let s=eligible();findWindow(s,'viceCounty');G.applyRole(s,'viceCounty');s.risks.push({month:s.month,title:'责任测试',due:s.month+6});G.next(s);assert.equal(s.career.application,null);assert.equal(s.career.role,'town');});
test('中央政府和党委岗位使用不同任职程序',()=>{assert.ok(C.procedures(C.byId('premier')).join().includes('国家主席提名'));assert.ok(C.procedures(C.byId('generalSecretary')).join().includes('中央委员会全体会议选举'));assert.ok(C.procedures(C.byId('minister')).join().includes('国务院总理提名'));});
test('副职不得越过分工，党委提案权限有区分',()=>{let s=G.initial('viceCounty','scenario'),w=C.world(s);assert.ok(G.propose(s,w.regions[1].id,'health'));assert.equal(G.propose(s,w.regions[0].id,'health'),null);s=G.initial('provinceParty','scenario');w=C.world(s);assert.ok(G.propose(s,w.regions[0].id,'industry'));assert.equal(G.propose(s,w.regions[0].id,'audit'),null);});
test('辖区提案扣本级资金、两个月反馈，运维持续增加',()=>{let s=G.initial('county','scenario'),w=C.world(s),cash=w.cash,local=s.cash,x=w.regions[0],old=x.health;assert.equal(G.propose(s,x.id,'health'),null);assert.equal(w.cash,cash-110*w.scale);assert.equal(s.cash,local);assert.ok(G.propose(s,x.id,'health'));G.next(s);assert.ok(x.health<old);G.next(s);assert.ok(x.health>old+10);assert.equal(x.upkeep,2.5);assert.equal(w.motions.length,0);});
test('高层不能直接修改基层地图',()=>{let s=G.initial('premier','scenario');assert.ok(G.build(s,118,'school'));assert.equal(s.cells[118].type,'empty');});
test('同级交流保留岗位与旧责任，不缩短晋升任职年限',()=>{let s=eligible(),since=s.career.since;s.risks.push({month:0,title:'历史记录',due:6});assert.equal(G.rotate(s),null);assert.equal(s.career.role,'town');assert.equal(s.career.since,since);assert.equal(s.risks.length,1);assert.ok(G.rotate(s));});
test('培训有等待期与冷却，不能叠加刷属性',()=>{let s=G.initial('province','scenario');assert.equal(G.train(s),null);assert.ok(G.train(s));G.next(s);G.next(s);G.next(s);assert.equal(s.career.trainedUntil,27);assert.ok(G.train(s));});
test('任职中途存档恢复后结果一致',()=>{let s=eligible();findWindow(s,'viceCounty');G.applyRole(s,'viceCounty');G.next(s);let copy=G.validate(JSON.parse(JSON.stringify(s)));G.next(s);G.next(copy);assert.deepEqual(copy,s);});
test('五年已结束的v2存档可续玩且保留原等级',()=>{let s=G.initial();s.version=2;s.month=60;s.level=2;s.ended='五年任期完成。你的每一次取舍，都留在这座城市。';delete s.career;G.validate(s);assert.equal(s.career.role,'city');assert.equal(s.ended,null);G.next(s);assert.equal(s.month,61);});
test('篡改角色、缺失层级或跳级申请会被拒绝',()=>{let s=G.initial();s.career.role='chairman';assert.throws(()=>G.validate(s));s=G.initial();s.career.world.pop();assert.throws(()=>G.validate(s));s=G.initial();s.career.application={target:'premier',from:'town',stage:0,nextAt:1};assert.throws(()=>G.validate(s));});
test('中央提案的反馈逐级传导，不在当月全局生效',()=>{let s=G.initial('premier','scenario'),w=C.world(s);G.propose(s,w.regions[0].id,'education');G.next(s);G.next(s);assert.equal(s.career.directives[0].tier,3);assert.equal(s.career.directives[0].due,4);let before=s.career.world.find(w=>w.tier===3).regions[0].education;G.next(s);assert.ok(s.career.world.find(w=>w.tier===3).regions[0].education<before);G.next(s);assert.ok(s.career.world.find(w=>w.tier===3).regions[0].education>before+2);for(let i=0;i<4;i++)G.next(s);assert.equal(s.career.directives.length,0);assert.ok(s.log.some(x=>x.text.includes('县区收到上级')));});
test('真实命令全程可达两条中央终点',()=>{const {run}=require('./journey.cjs');for(const route of [['town','viceCounty','county','viceCity','city','viceProvince','province','vicePremier','premier'],['town','townParty','viceCounty','county','countyParty','viceCity','city','cityParty','viceProvince','province','provinceParty','secretariat','standing','generalSecretary']]){const {s}=run(route);assert.equal(s.career.role,route.at(-1));assert.equal(s.month,420);G.validate(JSON.parse(JSON.stringify(s)));}});

