'use strict';
function civicMapLabel(s,i){const p=s.civic.parcels.find(p=>p.cell===i);if(p)return ({acquired:'征',approval:'批',ready:'待',auction:'拍',failed:'流',sold:'售'})[p.status];return s.civic.promises.some(p=>p.cell===i&&p.status==='active')?'诺':'';}
function civicPanel(which,m){const V=G.Civic,v=state.civic,locked=!!V.guard(state),dis=locked?'disabled':'',pos=selected===null?'尚未选择地块':`${Math.floor(selected/state.width)+1} 行 ${selected%state.width+1} 列`,pick=`<div class="notice"><strong>${pos}</strong><br>使用地图的“查看”工具选择地块，本页会保留。<button data-civic="map">前往地图选地</button></div>`,note='<p class="muted">本项目原创模拟数值；借鉴公开玩法流程，不是原作公式或现实政策规则。</p>';
 let html=locked?'<div class="notice">基层联系点台账只读；当前岗位请使用辖区治理。已有合同继续结算。</div>':'';
 if(which==='land'){
  html+='<h2>土地与出让</h2><p class="muted">整理 → 用途审批 → 三轮竞价 → 开发。土地收入进入建设专账，不能支付工资或招商费。</p>'+row('土地建设专账',fmt(v.landFund)+' 万')+row('累计专账建设支出',fmt(v.landSpent)+' 万')+meter('近12月土地收入依赖',V.dependency(state))+row('模拟经济周期',V.phase(state).name)+pick;
  const p=v.parcels.find(p=>p.cell===selected);
  if(p){const names={acquired:'已整理 · 待定用途',approval:'用途审批中',ready:'可挂牌',auction:'竞价中',failed:'流拍 · 可重新挂牌',sold:'已成交 · 开发商持有'};html+=row('当前宗地',names[p.status])+row('累计前期成本',fmt(p.cost)+' 万')+row('配套指数',fmt(V.support(state,p.cell,m))+'/100');if(p.status==='approval')html+=row('审批反馈',p.due-state.month+' 个月');if(p.status==='auction')html+=row('竞价进度',p.round+' / 3 轮')+row('当前最高出价',fmt(p.bid)+' 万');if(['acquired','ready','failed'].includes(p.status))html+=`<label class="field">申请用途<select id="landzone"><option value="home">住宅</option><option value="shop">商业</option><option value="factory">工业</option></select></label><button data-civic="zone" ${dis}>用途审批 · 10 万 / 2 月</button>`;if(['ready','failed'].includes(p.status))html+=`<label class="field">挂牌底价（万元）<input id="landprice" type="number" min="30" max="2000" value="${p.base||100}"></label><button data-civic="auction" ${dis}>挂牌 · 3 个月竞价</button>`;
  }else html+=`<p>未登记空地仍可按原方式直接建设。进入宗地流程后将锁定用途，不能绕过审批直接建房。</p><button data-civic="acquire" ${dis||selected===null?'disabled':''}>征收整理所选空地 · 25 万</button>`;
  html+='<h3>全部宗地</h3>'+(v.parcels.length?v.parcels.map(p=>`<div class="log"><button data-civic="locate" data-cell-id="${p.cell}">${Math.floor(p.cell/state.width)+1}行${p.cell%state.width+1}列</button> ${escape(({reserve:'储备',home:'住宅',shop:'商业',factory:'工业'})[p.zone])} · ${escape(({acquired:'待审批',approval:'审批中',ready:'待挂牌',auction:'竞价中',failed:'流拍',sold:'已出让'})[p.status])}${p.status==='sold'?' · '+fmt(p.bid)+' 万':''}</div>`).join(''):'<p class="muted">尚无宗地记录。</p>')+'<p class="muted">流拍不会返还整理费用，多次流拍降低本宗地竞价预期。土地依赖超过本模型的 45% 后压低居住吸引力及招商产出。成交由配套、底价及模拟经济周期共同决定。</p>';
 }else if(which==='livelihood'){
  html+='<h2>民生政策与年度实事</h2>'+meter('民生保障指数',V.index(state))+row('新增政策月支出',fmt(m.policyCost)+' 万')+row('已承诺月度工程款',fmt(m.commitmentCost)+' 万');
  html+=Object.entries(V.POLICIES).map(([k,d])=>`<label class="field">${d.name}<select data-public-policy="${k}" ${dis}>${[0,1,2,3].map(n=>`<option value="${n}" ${v.policies[k]===n?'selected':''}>${n} 档 · ${fmt(n*d.cost*state.pop/1000)} 万/月</option>`).join('')}</select></label>`).join('');
  html+='<p class="muted">四项政策按月进入基本民生支出。提高保障改善满意度与年度评价；培训帮助企业达到人才条件。政策不会凭空补充医生、教师或岗位。</p><h3>本年度承诺</h3><p>每年 1 月可选最多三项，不要求凑满。按 12 个月分期施工，年末验收；未足额投入或断路会失败，已付款不返还。</p>'+pick;
  const year=Math.floor(state.month/12)+1,list=v.promises.filter(p=>p.year===year);
  html+=`<label class="field">民生实事<select id="promisekind">${Object.entries(V.PROMISES).map(([k,d])=>`<option value="${k}">${d.name} · ${d.cost} 万 / ${fmt(d.cost/12)} 万每月</option>`).join('')}</select></label><button data-civic="pledge" ${locked||state.month%12!==0||selected===null||list.length>=3?'disabled':''}>承诺在所选空地落地</button>`;
  html+=list.map(p=>`<div class="log"><strong>${V.PROMISES[p.kind].name}</strong>${row('累计工程支付',fmt(p.paid)+' / '+p.cost+' 万')}${row('地块',Math.floor(p.cell/state.width)+1+'行'+(p.cell%state.width+1)+'列')}</div>`).join('');
  html+='<h3>年度验收报告</h3>'+(v.reports.length?[...v.reports].reverse().map(r=>`<div class="log">第 ${r.year} 年 · 完成 ${r.success} / 未完成 ${r.failed}${row('已付工程款',fmt(r.spent)+' 万')}${row('基层考核调整',(r.adjustment>=0?'+':'')+r.adjustment+' 分')}</div>`).join(''):'<p class="muted">年末验收后归档。完成设施落在地图，学校与医院仍须配置人员。</p>');
 }else{
  html+='<h2>产业与招商</h2><p>选择已建成的商业、工业或科技园，引入企业。基础建筑原有效益保留，企业达标运营后再增加岗位和产出。</p>'+row('模拟经济周期',V.phase(state).name)+row('当前企业新增岗位',fmt(m.enterprise.jobs)+' 个')+row('当前企业新增产出',fmt(m.enterprise.output)+' 万/月')+pick;
  html+=Object.entries(V.FIRMS).map(([k,d])=>`<article class="event"><h3>${d.name}</h3><p class="muted">需要${G.TYPES[d.type].name} · 教育 ${d.education}% · 水电 ${d.utility*100}% · 污染 ≤${d.pollution}。达标新增 ${d.jobs} 岗位，基础月产出 ${d.output} 万，随周期及土地依赖变化。</p><label>谈判条件<select id="offer-${k}"><option value="standard">标准服务 · ${d.cost} 万</option><option value="training">定向培训 · ${d.cost+15} 万 / 人才条件减10</option><option value="grant">改造支持 · ${d.cost+40} 万 / 污染容忍加10</option></select></label><button data-civic="negotiate" data-kind="${k}" ${dis||selected===null?'disabled':''}>发起谈判 · 2 个月后反馈</button></article>`).join('');
  html+='<h3>企业合同台账</h3>'+(v.firms.length?[...v.firms].reverse().map(f=>`<div class="log"><strong>${V.FIRMS[f.kind].name}</strong> · ${({negotiating:'谈判中',operating:'已签约',rejected:'未通过',closed:'已退出'})[f.status]}${row('已付费用',fmt(f.fee)+' 万')}${f.status==='operating'?row('连续未达标',f.offline+' 个月'):''}${['negotiating','operating'].includes(f.status)?`<button data-civic="exit" data-cell-id="${f.cell}" ${dis}>退出并清算 · 10 万</button>`:''}</div>`).join(''):'<p class="muted">暂无合同。谈判费用不因未通过退回；断路或配套不足时暂停新增效益，连续六个月不达标会退出。</p>');
 }
 return html+note;
}
function handleCivic(e){const b=e.target.closest('[data-civic]');if(!b)return false;const V=G.Civic,log=(s,t)=>{s.log.unshift({month:s.month,text:t});s.log=s.log.slice(0,150);},m=G.metrics(state),a=b.dataset.civic;if(a==='map'){worldView='map';tool='inspect';render();return true;}if(a==='locate'){selected=Number(b.dataset.cellId);worldView='map';tool='inspect';render();return true;}let err;if(['acquire','zone','auction'].includes(a))err=V.land(state,a,selected,$('landzone')?.value,Number($('landprice')?.value),m,log);if(a==='pledge')err=V.pledge(state,$('promisekind').value,selected,m,log);if(a==='negotiate')err=V.negotiate(state,b.dataset.kind,selected,$('offer-'+b.dataset.kind).value,m,log);if(a==='exit')err=V.exitFirm(state,Number(b.dataset.cellId),log);act(err);if(!err)toast('已记录，请推进月份查看反馈。');return true;}
