(function(root){
'use strict';
// Original simulation parameters, not the reference game's unpublished formulas.
const clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,n));
const POLICIES={aid:{name:'低保支持',cost:1.5},insurance:{name:'医保筹资',cost:2},pension:{name:'养老保障',cost:2},training:{name:'就业培训',cost:1}};
const PROMISES={school:{name:'社区学堂',type:'school',cost:180},clinic:{name:'基层诊疗站',type:'clinic',cost:220},housing:{name:'保障住房',type:'home',cost:96},park:{name:'口袋公园',type:'park',cost:84},water:{name:'饮水保障',type:'water',cost:192},power:{name:'供电改善',type:'power',cost:240},jobs:{name:'就业服务街区',type:'shop',cost:120},green:{name:'社区绿化',type:'park',cost:72}};
const FIRMS={manufacture:{name:'清源制造',type:'factory',jobs:180,output:75,cost:30,education:0,utility:.7,pollution:65},digital:{name:'青禾数据服务',type:'tech',jobs:220,output:110,cost:55,education:45,utility:.95,pollution:40},retail:{name:'邻里商贸',type:'shop',jobs:100,output:45,cost:18,education:0,utility:.6,pollution:80}};
function init(){return {policies:{aid:0,insurance:0,pension:0,training:0},promises:[],reports:[],parcels:[],firms:[],receipts:[],landFund:0,landSpent:0,scoreAdjustment:0};}
function guard(s){return s.ended?'职业生涯已结束。':s.level>0?'本页为基层联系点台账，县级以上请使用辖区治理。':null;}
function at(s,i){return Number.isInteger(i)&&i>=0&&i<s.cells.length;}
function occupied(s,i){return s.civic.parcels.some(p=>p.cell===i)||s.civic.promises.some(p=>p.cell===i&&p.status==='active')||s.projects.some(p=>p.cell===i);}
function lock(s,i){if(s.civic.parcels.some(p=>p.cell===i))return '宗地已进入土地流程或已出让，不能直接建设或拆除。';if(s.civic.promises.some(p=>p.cell===i&&p.status==='active'))return '该地块已用于年度民生承诺。';if(s.civic.firms.some(f=>f.cell===i&&!['rejected','closed'].includes(f.status)))return '该建筑有招商合同，请先退出企业并完成清算。';return null;}
function support(s,i,m){const x=i%s.width,y=Math.floor(i/s.width);let linked=false;for(const j of m.linked)if(Math.abs(j%s.width-x)+Math.abs(Math.floor(j/s.width)-y)===1)linked=true;return linked?clamp(35+m.education*.2+m.health*.2+m.utility*25):0;}
function phase(s){const values=[{name:'复苏',factor:.92},{name:'扩张',factor:1.15},{name:'降温',factor:.8},{name:'调整',factor:.68}];return values[Math.floor(s.month/12)%4];}
function policyCost(s){return Object.entries(POLICIES).reduce((n,[k,p])=>n+s.civic.policies[k]*p.cost,0)*s.pop/1000;}
function index(s){return Object.values(s.civic.policies).reduce((a,b)=>a+b,0)/12*100;}
function installment(s){return s.civic.promises.filter(p=>p.status==='active').reduce((n,p)=>n+Math.min(p.cost-p.paid,p.cost/12),0);}
function dependency(s){const a=s.civic.receipts.reduce((n,r)=>n+r.land,0),b=s.civic.receipts.reduce((n,r)=>n+r.regular,0);return a/Math.max(1,a+b)*100;}
function effects(s,linked,education,utility){let jobs=0,output=0;for(const f of s.civic.firms){const d=FIRMS[f.kind],c=s.cells[f.cell];if(f.status!=='operating'||c.wait||c.type!==d.type)continue;const x=f.cell%s.width,y=Math.floor(f.cell/s.width);if(![...linked].some(j=>Math.abs(j%s.width-x)+Math.abs(Math.floor(j/s.width)-y)===1)||education+s.civic.policies.training*5+(f.offer==='training'?10:0)<d.education||utility<d.utility||s.pollution>d.pollution+(f.offer==='grant'?10:0))continue;jobs+=d.jobs;output+=d.output*phase(s).factor*(1-clamp(dependency(s)-45,0,50)/200);}
 return {jobs,output};}
function setPolicy(s,key,value,log){const e=guard(s);if(e)return e;if(!POLICIES[key]||!Number.isInteger(value)||value<0||value>3)return '政策档位必须为 0–3。';s.civic.policies[key]=value;log(s,POLICIES[key].name+'调整为 '+value+' 档，下月结算。');return null;}
function pledge(s,kind,cell,m,log){const e=guard(s);if(e)return e;const d=PROMISES[kind],year=Math.floor(s.month/12)+1;if(s.month%12!==0)return '年度民生承诺只在每年 1 月选定。';if(!d||!at(s,cell)||s.cells[cell].type!=='empty'||occupied(s,cell))return '请在地图选择未占用的空地。';const list=s.civic.promises.filter(p=>p.year===year);if(list.length>=3||list.some(p=>p.kind===kind))return '每年最多三项，每类只能承诺一次。';if(support(s,cell,m)===0)return '承诺地块需要先连接道路。';if(s.cash<m.operating*3||s.payables>0)return '请先保障三个月基本支出并清理欠款。';s.civic.promises.push({kind,cell,year,cost:d.cost,paid:0,status:'active',role:s.career.role});log(s,'年度承诺：'+d.name+'，总额 '+d.cost+' 万，按 12 个月施工支付并于年底验收。');return null;}
function land(s,action,cell,zone,price,m,log){const e=guard(s);if(e)return e;if(!at(s,cell))return '请先选择地图地块。';let p=s.civic.parcels.find(p=>p.cell===cell);
 if(action==='acquire'){if(s.cells[cell].type!=='empty'||occupied(s,cell))return '只可登记未占用空地。';if(s.cash-25<m.operating*3||s.payables>0)return '征收整理支出 25 万，需保留三个月基本支出。';s.cash-=25;s.civic.parcels.push({cell,zone:'reserve',status:'acquired',cost:25,due:0,base:0,bid:0,round:0,failures:0});log(s,'宗地征收整理完成，支出 25 万；成本不因流拍返还。');return null;}
 if(!p)return '请先登记并整理宗地。';
 if(action==='zone'){if(!['acquired','ready','failed'].includes(p.status)||!['home','shop','factory'].includes(zone))return '宗地当前不能申请该用途。';if(s.cash-10<m.operating*3||s.payables>0)return '用途变更费用 10 万，需保障基本支出。';s.cash-=10;p.cost+=10;p.zone=zone;p.status='approval';p.due=s.month+2;log(s,'宗地用途申请已提交，模拟两个月审批。');return null;}
 if(action==='auction'){if(!['ready','failed'].includes(p.status)||!['home','shop','factory'].includes(p.zone))return '须用途审批通过后挂牌。';if(!Number.isFinite(price)||price<30||price>2000)return '挂牌底价范围为 30–2000 万。';p.status='auction';p.base=price;p.bid=0;p.round=0;p.due=s.month+3;log(s,'宗地挂牌，底价 '+price+' 万，三个月竞价；底价高或配套不足可能流拍。');return null;}
 return '未知土地操作。';}
function negotiate(s,kind,cell,offer,m,log){const e=guard(s);if(e)return e;const d=FIRMS[kind];if(!d||!at(s,cell)||!['standard','training','grant'].includes(offer))return '请选择企业、谈判条件及相应建筑。';const c=s.cells[cell];if(c.type!==d.type||c.wait)return '该企业需要已竣工的'+({factory:'工业厂房',tech:'科技园',shop:'商业建筑'}[d.type])+'。';if(s.civic.firms.some(f=>f.cell===cell&&!['rejected','closed'].includes(f.status))||s.civic.firms.some(f=>f.kind===kind&&!['rejected','closed'].includes(f.status)))return '该地块或该企业已有合同。';if(support(s,cell,m)===0)return '建筑未接入有效道路。';const fee=d.cost+(offer==='grant'?40:offer==='training'?15:0);if(s.cash-fee<m.operating*3||s.payables>0)return '谈判费用 '+fee+' 万，需保障三个月基本支出。';s.cash-=fee;s.civic.firms.push({kind,cell,offer,fee,status:'negotiating',due:s.month+2,offline:0});log(s,d.name+'开始谈判，支出 '+fee+' 万，两个月后审核配套；失败不退款。');return null;}
function exitFirm(s,cell,log){const e=guard(s);if(e)return e;const f=s.civic.firms.find(f=>f.cell===cell&&['negotiating','operating'].includes(f.status));if(!f)return '没有可退出的合同。';if(s.cash<10)return '合同清算需 10 万。';s.cash-=10;f.status='closed';log(s,FIRMS[f.kind].name+'已退出，原建筑保留，专项债继续留账。');return null;}
function tick(s,m,paid,log){const v=s.civic;v.scoreAdjustment=0;let funds=paid;for(const p of v.promises.filter(p=>p.status==='active')){const amount=Math.min(p.cost-p.paid,p.cost/12,funds);p.paid+=amount;funds-=amount;}
 let landIncome=0;
 for(const p of v.parcels){if(p.status==='approval'&&p.due<=s.month){p.status='ready';log(s,'宗地用途审批通过，可挂牌出让。');}
 else if(p.status==='auction'){p.round++;const service=support(s,p.cell,m),cap=Math.round((80+service*2)*phase(s).factor*Math.max(.55,1-p.failures*.1));if(service>0&&cap>=p.base){p.bid=Math.max(p.bid,Math.min(cap,Math.round(p.base+(cap-p.base)*p.round/3)));}if(p.due<=s.month){if(p.bid>=p.base&&service>0){p.status='sold';landIncome+=p.bid;v.landFund+=p.bid;s.cells[p.cell]={type:p.zone,wait:2,owner:'private'};log(s,'宗地成交 '+p.bid+' 万，进入土地建设专账；开发商两个月后交付建筑。');}else{p.status='failed';p.failures++;log(s,'宗地流拍：底价过高或配套不足，前期成本不退；可调整底价重新挂牌。');}}}}
 v.receipts.push({month:s.month,regular:m.income,land:landIncome});v.receipts=v.receipts.slice(-12);
 for(const f of v.firms){const d=FIRMS[f.kind],eligible=s.cells[f.cell].type===d.type&&s.cells[f.cell].wait===0&&support(s,f.cell,m)>0&&m.education+v.policies.training*5+(f.offer==='training'?10:0)>=d.education&&m.utility>=d.utility&&s.pollution<=d.pollution+(f.offer==='grant'?10:0);
 if(f.status==='negotiating'&&f.due<=s.month){f.status=eligible?'operating':'rejected';log(s,d.name+(eligible?'落地运营，就业与税源从下月体现。':'谈判未通过：教育、水电、环境或路网不达标。'));}
 else if(f.status==='operating'){f.offline=eligible?0:f.offline+1;if(f.offline>=6){f.status='closed';log(s,d.name+'因连续六个月配套不达标退出。');}}}
 if(s.month%12===0){const list=v.promises.filter(p=>p.status==='active'&&p.year===s.month/12);let success=0;for(const p of list){const ok=p.paid>=p.cost-.01&&s.cells[p.cell].type==='empty'&&support(s,p.cell,m)>0;p.status=ok?'completed':'failed';if(ok){s.cells[p.cell]={type:PROMISES[p.kind].type,wait:0,owner:'public'};success++;}log(s,PROMISES[p.kind].name+(ok?'年度验收通过，设施落地；公共服务仍须配备人员。':'年度验收未通过，已付工程款不退，地块释放。'));}if(list.length){const failed=list.length-success;v.scoreAdjustment=success*2-failed*5;s.reputation=clamp(s.reputation+success-failed*3);v.reports.push({year:s.month/12,success,failed,spent:list.reduce((n,p)=>n+p.paid,0),adjustment:v.scoreAdjustment});}}
}
function remap(s,fn){for(const list of [s.civic.parcels,s.civic.promises,s.civic.firms])for(const p of list)p.cell=fn(p.cell);}
function validate(s){const v=s.civic;if(!v||!v.policies)throw Error('缺少治理扩展台账。');for(const k of Object.keys(POLICIES))if(!Number.isInteger(v.policies[k])||v.policies[k]<0||v.policies[k]>3)throw Error('民生档位不正确。');for(const k of ['landFund','landSpent'])if(!Number.isFinite(v[k])||v[k]<0)throw Error('土地资金不正确。');if(!Number.isFinite(v.scoreAdjustment)||v.scoreAdjustment< -15||v.scoreAdjustment>6)throw Error('验收考核不正确。');for(const k of ['promises','reports','parcels','firms','receipts'])if(!Array.isArray(v[k])||v[k].length>(k==='parcels'?4096:500))throw Error('治理记录格式不正确。');
 const finite=n=>Number.isFinite(n)&&n>=0,int=n=>Number.isInteger(n)&&n>=0;
 if(v.parcels.some(p=>!at(s,p.cell)||!['reserve','home','shop','factory'].includes(p.zone)||!['acquired','approval','ready','auction','failed','sold'].includes(p.status)||!['cost','due','base','bid','round','failures'].every(k=>finite(p[k]))||p.round>3||p.status==='auction'&&(p.base<30||p.base>2000||p.due<=s.month)||p.status==='approval'&&p.due<=s.month||p.status==='sold'&&(s.cells[p.cell].type!==p.zone||s.cells[p.cell].owner!=='private')||p.status!=='sold'&&s.cells[p.cell].type!=='empty')||new Set(v.parcels.map(p=>p.cell)).size!==v.parcels.length)throw Error('宗地流程不正确。');
 if(v.promises.some(p=>!PROMISES[p.kind]||!at(s,p.cell)||!int(p.year)||p.year<1||p.year>35||p.cost!==PROMISES[p.kind].cost||!finite(p.paid)||p.paid>p.cost+.01||!['active','completed','failed'].includes(p.status)||p.status==='active'&&(p.year!==Math.floor(s.month/12)+1||s.cells[p.cell].type!=='empty')||p.status==='completed'&&p.paid<p.cost-.01))throw Error('民生承诺数据不正确。');
 for(const year of new Set(v.promises.map(p=>p.year))){const list=v.promises.filter(p=>p.year===year);if(list.length>3||new Set(list.map(p=>p.kind)).size!==list.length)throw Error('年度承诺重复或超额。');}
 if(v.firms.some(f=>!FIRMS[f.kind]||!at(s,f.cell)||!['standard','training','grant'].includes(f.offer)||!['negotiating','operating','rejected','closed'].includes(f.status)||!finite(f.fee)||!int(f.due)||!int(f.offline)||['negotiating','operating'].includes(f.status)&&s.cells[f.cell].type!==FIRMS[f.kind].type))throw Error('招商台账不正确。');
 const active=v.firms.filter(f=>['negotiating','operating'].includes(f.status));if(new Set(active.map(f=>f.cell)).size!==active.length||new Set(active.map(f=>f.kind)).size!==active.length)throw Error('招商合同重复。');const reserved=[...v.parcels.filter(p=>p.status!=='sold'),...v.promises.filter(p=>p.status==='active'),...s.projects];if(new Set(reserved.map(p=>p.cell)).size!==reserved.length)throw Error('地块被重复预留。');if(v.receipts.length>12||v.receipts.some(r=>!int(r.month)||r.month>s.month||!finite(r.regular)||!finite(r.land)))throw Error('土地收入记录不正确。');if(v.reports.some(r=>!int(r.year)||!int(r.success)||!int(r.failed)||r.success+r.failed>3||!finite(r.spent)||!Number.isFinite(r.adjustment)))throw Error('民生验收记录不正确。');
}
const api={POLICIES,PROMISES,FIRMS,init,guard,lock,support,phase,policyCost,index,installment,dependency,effects,setPolicy,pledge,land,negotiate,exitFirm,tick,remap,validate};if(typeof module!=='undefined')module.exports=api;else root.Civic=api;
})(globalThis);
