const {test}=require('node:test'),assert=require('node:assert/strict'),G=require('./engine'),V=G.Civic,log=(s,t)=>s.log.unshift({month:s.month,text:t}),land=(s,a,i,z,p)=>V.land(s,a,i,z,p,G.metrics(s),log),pledge=(s,k,i)=>V.pledge(s,k,i,G.metrics(s),log),firm=(s,k,i,o='standard')=>V.negotiate(s,k,i,o,G.metrics(s),log);
function months(s,n){for(let i=0;i<n;i++){for(const e of [...s.events])G.resolve(s,e.id,1);assert.equal(G.next(s),null);}}
test('v4迁移保持大地图资金及职业，v5缺失台账不能伪装迁移',()=>{const s=G.initial();G.expand(s,24,20);s.version=4;delete s.civic;const copy=G.validate(structuredClone(s));assert.equal(copy.width,24);assert.equal(copy.cash,s.cash);assert.equal(copy.version,7);delete copy.civic;assert.throws(()=>G.validate(copy));});
test('民生档位影响实际成本和保障指数，不能越权或越界',()=>{const s=G.initial(),m=G.metrics(s);assert.equal(V.setPolicy(s,'aid',2,log),null);assert.ok(Math.abs(G.metrics(s).policyCost-4.35)<1e-8);assert.ok(Math.abs(G.metrics(s).expense-m.expense-4.35)<1e-8);assert.ok(V.index(s)>0);assert.ok(V.setPolicy(s,'aid',4,log));assert.ok(V.setPolicy(G.initial('county'),'aid',1,log));});
test('年度承诺预留地块按月付款，年末真实落地并归档',()=>{const s=G.initial();assert.equal(pledge(s,'school',118),null);assert.ok(G.build(s,118,'home'));assert.ok(land(s,'acquire',118));const cost=G.metrics(s).commitmentCost;assert.equal(cost,15);months(s,1);assert.equal(s.civic.promises[0].paid,15);assert.equal(s.cells[118].type,'empty');assert.ok(pledge(s,'clinic',119));months(s,11);assert.equal(s.civic.promises[0].status,'completed');assert.equal(s.cells[118].type,'school');assert.equal(s.civic.reports[0].success,1);assert.equal(s.civic.reports[0].adjustment,2);G.validate(structuredClone(s));});
test('年度承诺最多三项不重复，失败不返还且影响考核',()=>{const s=G.initial();assert.equal(pledge(s,'school',118),null);assert.ok(pledge(s,'school',119));assert.equal(pledge(s,'park',119),null);assert.equal(pledge(s,'housing',120),null);assert.ok(pledge(s,'water',121));months(s,11);G.build(s,7*18+10,'demolish');months(s,1);assert.equal(s.civic.promises[0].status,'failed');assert.equal(s.civic.promises[0].paid,180);assert.equal(s.cells[118].type,'empty');assert.equal(s.civic.reports[0].failed,3);assert.equal(s.civic.reports[0].adjustment,-15);});
test('土地流程锁定地块、审批延迟、竞价到账分账且不重复',()=>{const s=G.initial();assert.equal(land(s,'acquire',118),null);assert.equal(s.cash,1475);assert.ok(G.build(s,118,'home'));assert.ok(land(s,'auction',118,null,100));assert.equal(land(s,'zone',118,'home'),null);months(s,2);assert.equal(s.civic.parcels[0].status,'ready');assert.equal(land(s,'auction',118,null,100),null);months(s,2);assert.equal(s.civic.landFund,0);months(s,1);assert.equal(s.civic.parcels[0].status,'sold');assert.ok(s.civic.landFund>=100);assert.equal(s.cells[118].owner,'private');const fund=s.civic.landFund;months(s,3);assert.equal(s.civic.landFund,fund);assert.ok(land(s,'auction',118,null,100));assert.ok(G.build(s,118,'demolish'));G.validate(structuredClone(s));});
test('过高底价流拍不退前期成本，允许调整后重新挂牌',()=>{const s=G.initial();land(s,'acquire',118);land(s,'zone',118,'shop');months(s,2);land(s,'auction',118,null,2000);months(s,3);assert.equal(s.civic.parcels[0].status,'failed');assert.equal(s.civic.parcels[0].cost,35);assert.equal(s.civic.landFund,0);assert.equal(land(s,'auction',118,null,30),null);months(s,3);assert.equal(s.civic.parcels[0].status,'sold');});
test('土地专账限定用途，不进入工资现金，可用于预算内公共建设',()=>{const s=G.initial();s.civic.landFund=300;const cash=s.cash;assert.ok(G.build(s,118,'factory','land'));assert.equal(G.build(s,118,'school','land'),null);assert.equal(s.cash,cash);assert.equal(s.civic.landFund,120);assert.equal(s.civic.landSpent,180);assert.equal(s.budget.spent,180);s.cash=0;s.staff.admin=90;G.next(s);assert.equal(s.civic.landFund,120);assert.ok(s.payables>0);});
test('招商谈判延期、重复阻止、运营岗位税源与路网联动',()=>{const s=G.initial(),m=G.metrics(s);assert.equal(firm(s,'manufacture',8*18+5),null);assert.ok(firm(s,'manufacture',8*18+5));assert.equal(G.metrics(s).enterprise.jobs,0);months(s,2);assert.equal(s.civic.firms[0].status,'operating');assert.equal(G.metrics(s).enterprise.jobs,180);assert.ok(G.metrics(s).income>m.income);assert.ok(G.build(s,8*18+5,'demolish'));G.build(s,7*18+5,'demolish');assert.equal(G.metrics(s).enterprise.jobs,0);months(s,6);assert.equal(s.civic.firms[0].status,'closed');assert.equal(G.build(s,8*18+5,'demolish'),null);});
test('企业退出清算保留建筑，失败谈判不退款，谈判条件实际作用',()=>{const s=G.initial();s.pollution=70;assert.equal(firm(s,'manufacture',149,'grant'),null);months(s,2);assert.equal(s.civic.firms[0].status,'operating');assert.equal(G.metrics(s).enterprise.jobs,180);assert.equal(V.exitFirm(s,149,log),null);assert.equal(s.cells[149].type,'factory');assert.equal(G.metrics(s).enterprise.jobs,0);const s2=G.initial();s2.pollution=90;firm(s2,'manufacture',149);months(s2,2);assert.equal(s2.civic.firms[0].status,'rejected');assert.equal(s2.civic.firms[0].fee,30);});
test('新增三类地块台账随扩图重映射，中途存档月度结算一致',()=>{const s=G.initial();land(s,'acquire',118);land(s,'zone',118,'home');pledge(s,'park',119);firm(s,'manufacture',149);G.expand(s,30,24);assert.equal(s.civic.parcels[0].cell,190);assert.equal(s.civic.promises[0].cell,191);assert.equal(s.civic.firms[0].cell,245);const copy=G.validate(structuredClone(s));months(s,8);months(copy,8);assert.deepEqual(s,copy);});
test('篡改宗地、承诺、合同或资金不能导入',()=>{for(const corrupt of [s=>s.civic.landFund=-1,s=>s.civic.policies.aid=99,s=>s.civic.parcels.push({cell:9999}),s=>s.civic.promises.push({kind:'fake'}),s=>s.civic.firms.push({kind:'fake'}),s=>s.civic.receipts.push({month:0,land:-1,regular:0})]){const s=G.initial();corrupt(s);assert.throws(()=>G.validate(s));}});
