'use strict';
function staffingPanel(m){const S=G.Staffing,e=state.establishment,limits=S.ceilings(state,m),locked=!!state.ended||state.level>0;let html='<h2>分类编制与人员</h2><p>行政、教育事业、医疗事业分别核定，互不挤占。办公楼、服务站、学校、医院增加承载条件，编制调整须另行申请。</p>';if(state.level>0)html+='<div class="notice">此处为基层联系点只读台账，已有招录和增编申请继续办理；本级工作使用辖区治理。</div>';
 html+=row('全部在岗人员',Object.values(state.staff).reduce((a,b)=>a+b,0)+' 人')+row('全部在岗月工资',fmt(m.wages)+' 万')+row('待到岗新增月工资',fmt(state.recruitment.filter(r=>r.delta>0).reduce((n,r)=>n+S.ROLES[r.role].salary,0))+' 万');
 for(const [k,d] of Object.entries(S.ROLES)){const incoming=state.recruitment.filter(r=>r.role===k&&r.delta>0).length,outgoing=state.recruitment.filter(r=>r.role===k&&r.delta<0).length,used=S.used(state,k),app=e.applications.find(a=>a.role===k);html+=`<article class="staff-card"><h3>${d.category}</h3><p class="muted">${d.name} · 月薪 ${d.salary} 万/人</p>${row('核定额度',e.quotas[k]+' 名')}${row('在岗 / 待到岗 / 待调出',state.staff[k]+' / '+incoming+' / '+outgoing)}${row('当前占编 / 空编',used+' / '+Math.max(0,e.quotas[k]-used))}${row('当前条件可申报总额',limits[k]+' 名')}<div class="actions"><button data-hire="${k}" data-delta="-1" aria-label="减少${d.name}" ${locked||state.staff[k]<=outgoing?'disabled':''}>申请调出</button><button data-hire="${k}" data-delta="1" aria-label="招录${d.name}" ${locked||used>=e.quotas[k]?'disabled':''}>${k==='admin'?'申请招录':'公开招聘'} · 8 万</button></div>`;
 if(app)html+=`<div class="notice">申请核增 ${app.amount} 名 · ${app.due-state.month} 个月后反馈</div>`;else{const n=Math.max(1,Math.min(5,limits[k]-e.quotas[k])),why=S.reasons(state,k,n,m),f=S.financial(state,k,n,m);html+=`<label class="field">申请新增名额<input id="quota-${k}" type="number" min="1" max="10" value="${n}" ${locked?'disabled':''}></label><button data-staffing="request" data-category="${k}" ${locked||limits[k]<=e.quotas[k]?'disabled':''}>上报增编 · 3 个月审核</button><p class="muted">按新增 ${n} 名预估：含现有核定额度满员工资及并行增编，六个月基本支出需 ${fmt(f.reserve)} 万，月度结余 ${fmt(f.balance)} 万。${why.length?'当前条件：'+escape(why.join('；')):'当前具备申报条件，审批时重新审核。'}</p>`;}html+='</article>';}
 html+='<h3>行政办公承载</h3>'+row('行政中心扩建等级',e.officeLevel+' / 3')+row('已连通服务站',m.count.service||0)+row('可容纳行政人员',S.officeCapacity(state,m.count)+' 人')+meter('政务服务承载',m.adminEfficiency*100);if(e.upgradeDue)html+=`<p>办公扩建施工中，${e.upgradeDue-state.month} 个月后完工。</p>`;else html+=`<button data-staffing="office" ${locked||e.officeLevel>=3?'disabled':''}>扩建行政中心 · ${120*(e.officeLevel+1)} 万</button>`;
 html+='<p class="muted">每级办公扩建增加 6 人容量，政务服务站增加 10 人容量；两者均不自动增加编制。新增编制需人口需求、已连通设施与持续财力共同支持。人口减少或设施拆除不会立即解聘现有人员，但服务能力可能下降。</p>'+meter('教育覆盖',m.education)+meter('医疗覆盖',m.health)+'<h3>人员办理中</h3>'+(state.recruitment.length?state.recruitment.map(r=>row(S.ROLES[r.role].name+(r.delta>0?'招录/招聘':'调出'),(r.due-state.month)+' 个月')).join(''):'<p class="muted">暂无办理事项。</p>');
 html+='<div class="notice">招录/招聘 2 个月到岗；调出 3 个月办结，期间仍占编并发薪。编制获批不等于已招到人。办理费、年限、额度和工资均为游戏参数。</div><h3>增编审批档案</h3>'+(e.records.length?[...e.records].reverse().map(a=>`<div class="log">第 ${a.finished} 月 · ${S.ROLES[a.role].category} +${a.amount} · ${a.approved?'已批准':'已退回'}<small>${escape(a.reason||'额度已入账，可按空编招录。')}</small></div>`).join(''):'<p class="muted">暂无审批记录。</p>');
 html+='<h3>现实分类说明</h3><p class="muted">机关行政人员通常使用行政编制；公办学校教师、公立医疗机构人员按本版选用的事业编制模型管理。事业单位的管理岗、专业技术岗不因名称含“行政”而成为行政编制。医院存在备案制、人员总量等不同管理方式，也有编外人员；本版暂未模拟这些分支。政务服务站是办公设施，不据此自动确定工作人员编制性质。国企员工、劳务派遣和编外合同人员不占本版行政或事业编制。</p>';return html;}
function handleStaffing(event){const b=event.target.closest('[data-staffing]');if(!b)return false;if(b.dataset.staffing==='office')act(G.upgradeOffice(state));else act(G.requestQuota(state,b.dataset.category,Number($('quota-'+b.dataset.category).value)));return true;}
