const {test}=require('node:test'),a=require('node:assert/strict'),G=require('./engine'),S=G.Staffing;
function city(){const s=G.initial();s.pop=4000;s.cash=10000;s.policy.welfare=20;s.budget.limit=3000;G.build(s,126+18+10,'power');G.build(s,126+18+11,'water');G.build(s,126+18+12,'factory');G.build(s,118,'school');G.build(s,119,'clinic');G.build(s,120,'home');G.build(s,121,'home');G.build(s,122,'home');for(let n=0;n<2;n++)G.next(s);s.pop=4000;return s;}
test('三类编制独立，待到岗占编，调出完成前仍占编',()=>{const s=G.initial();for(let n=0;n<12;n++)a.equal(G.hire(s,'teachers',1),null);a.ok(G.hire(s,'teachers',1));a.equal(G.hire(s,'doctors',1),null);a.equal(G.hire(s,'admin',1),null);G.next(s);G.next(s);a.equal(s.staff.teachers,12);G.hire(s,'teachers',-1);a.ok(G.hire(s,'teachers',1));for(let n=0;n<3;n++)G.next(s);a.equal(G.hire(s,'teachers',1),null);G.validate(structuredClone(s));});
test('建筑和人口不自动增编，办公扩建有预算工期，服务站须连通',()=>{const s=city(),q=structuredClone(s.establishment.quotas);a.equal(G.upgradeOffice(s),null);a.equal(s.establishment.officeLevel,0);a.ok(G.upgradeOffice(s));G.next(s);G.next(s);a.equal(s.establishment.officeLevel,1);a.deepEqual(s.establishment.quotas,q);a.equal(S.officeCapacity(s,G.metrics(s).count),18);a.equal(G.build(s,6*18+1,'service'),null);G.next(s);G.next(s);a.equal(S.officeCapacity(s,G.metrics(s).count),28);G.build(s,7*18+1,'demolish');a.equal(S.officeCapacity(s,G.metrics(s).count),18);});
test('增编三个月重新审核，批准只改对应额度不自动招聘',()=>{const s=city(),m=G.metrics(s);a.ok(S.ceilings(s,m).teachers>=17);a.equal(G.requestQuota(s,'teachers',5),null);a.ok(G.requestQuota(s,'teachers',1));const before=s.staff.teachers;G.next(s);G.next(s);a.equal(s.establishment.quotas.teachers,12);G.next(s);a.equal(s.establishment.quotas.teachers,17);a.equal(s.staff.teachers,before);a.equal(s.establishment.quotas.doctors,12);a.equal(s.establishment.records[0].approved,true);});
test('审批期拆除必要设施则退回，不清空既有人员和核定编制',()=>{const s=city();a.equal(G.requestQuota(s,'teachers',5),null);G.build(s,118,'demolish');for(let n=0;n<3;n++)G.next(s);a.equal(s.establishment.quotas.teachers,12);a.equal(s.establishment.records[0].approved,false);});
test('满员工资与并行增编承诺纳入审核，欠款、权限与非法名额拒绝',()=>{const s=city(),m=G.metrics(s),before=S.financial(s,'teachers',5,m);a.equal(G.requestQuota(s,'doctors',1),null);a.ok(S.financial(s,'teachers',5,m).reserve>before.reserve);s.payables=1;a.ok(G.requestQuota(s,'teachers',5));a.ok(G.requestQuota(s,'fake',5));a.ok(G.requestQuota(s,'teachers',0));a.ok(G.requestQuota(G.initial('county'),'admin',1));a.ok(G.hire(G.initial('county'),'admin',1));});
test('旧存档保留在岗和待到岗，超旧共享限额不清退，坏新档拒绝',()=>{const s=G.initial();s.version=5;delete s.establishment;s.staff.teachers=50;s.recruitment=[{role:'teachers',delta:1,due:2}];const copy=G.validate(structuredClone(s));a.equal(copy.establishment.quotas.teachers,51);a.equal(copy.staff.teachers,50);a.equal(copy.cash,s.cash);a.equal(copy.version,7);copy.establishment.quotas.teachers=50;a.throws(()=>G.validate(copy));});
test('增编与办公扩建中途保存可确定性续办',()=>{const s=city();G.requestQuota(s,'teachers',1);G.upgradeOffice(s);const copy=G.validate(structuredClone(s));for(let n=0;n<4;n++){G.next(s);G.next(copy);}a.deepEqual(copy,s);});
