(function(root){
'use strict';
const ROLES={admin:{name:'机关行政人员',category:'行政编制',salary:1.2},teachers:{name:'公办学校教师',category:'事业编制 · 教育',salary:1.3},doctors:{name:'公立医疗人员',category:'事业编制 · 医疗',salary:1.5}};
function init(s){return {quotas:Object.fromEntries(Object.keys(ROLES).map(k=>[k,Math.max(12,(s?.staff?.[k]||0)+(s?.recruitment||[]).filter(r=>r.role===k&&r.delta>0).length)])),applications:[],records:[],officeLevel:0,upgradeDue:0};}
function used(s,k){return s.staff[k]+s.recruitment.filter(r=>r.role===k&&r.delta>0).length;}
function officeCapacity(s,count){return 12+s.establishment.officeLevel*6+(count.service||0)*10;}
function ceilings(s,m){return {admin:Math.max(12,Math.min(1000,Math.ceil(s.pop/220)+2,officeCapacity(s,m.count))),teachers:Math.max(12,Math.min(1000,Math.ceil(s.pop/180)+2,(m.count.school||0)*17)),doctors:Math.max(12,Math.min(1000,Math.ceil(s.pop/160)+2,(m.count.clinic||0)*19))};}
function financial(s,k,amount,m){const vacancies=Object.keys(ROLES).reduce((n,key)=>n+Math.max(0,s.establishment.quotas[key]-s.staff[key])*ROLES[key].salary,0),committed=s.establishment.applications.filter(a=>a.role!==k).reduce((n,a)=>n+a.amount*ROLES[a.role].salary,0),extra=vacancies+committed+amount*ROLES[k].salary;return {reserve:(m.operating+extra)*6,balance:m.balance-extra};}
function reasons(s,k,amount,m){const a=[];if(!ROLES[k]||!Number.isInteger(amount)||amount<1||amount>10)return ['申请名额须为 1–10 人'];if(s.ended)a.push('职业生涯已结束');if(s.level>0)a.push('基层联系点只读');if(s.establishment.quotas[k]+amount>ceilings(s,m)[k])a.push('超过当前人口及已连通设施对应的可申报额度');const f=financial(s,k,amount,m);if(s.payables>0||s.annualGap)a.push('先清理欠款及本年度基本支出缺口');if(s.cash<f.reserve)a.push('需保障增编后六个月基本支出');if(f.balance<0)a.push('增编后预计月度收支为负');return a;}
function request(s,k,amount,m,log){const why=reasons(s,k,amount,m);if(s.establishment.applications.some(a=>a.role===k))why.push('该类别已有申请');if(why.length)return why.join('；');s.establishment.applications.push({role:k,amount,due:s.month+3,submitted:s.month});log(s,'上报'+ROLES[k].category+'增编 '+amount+' 名，按管理权限审核，模拟三个月后反馈。');return null;}
function upgrade(s,m,log){const e=s.establishment;if(s.ended||s.level>0)return '当前不能扩建基层办公设施。';if(e.upgradeDue)return '办公扩建正在施工。';if(e.officeLevel>=3)return '行政中心已完成三级扩建，可增设政务服务站。';const cost=120*(e.officeLevel+1);if(s.budget.spent+cost>s.budget.limit)return '年度建设预算不足。';if(s.cash-cost<m.operating*3||s.payables>0)return '扩建后需保留三个月基本支出并清理欠款。';s.cash-=cost;s.budget.spent+=cost;e.upgradeDue=s.month+2;log(s,'行政中心办公扩建支出 '+cost+' 万，两个月后增加办公容量；不自动增加行政编制。');return null;}
function tick(s,getMetrics,log){const e=s.establishment;if(e.upgradeDue&&e.upgradeDue<=s.month){e.upgradeDue=0;e.officeLevel++;log(s,'行政中心办公扩建完成，办公容量增加 6 人，行政编制须另行申报。');}for(const a of [...e.applications])if(a.due<=s.month){const why=reasons(s,a.role,a.amount,getMetrics(s)).filter(x=>x!=='基层联系点只读');if(why.length){log(s,ROLES[a.role].category+'增编申请退回：'+why.join('；'));}else{e.quotas[a.role]+=a.amount;log(s,ROLES[a.role].category+'核增 '+a.amount+' 名；尚未招聘人员，不立即增加工资。');}e.records.push({...a,finished:s.month,approved:why.length===0,reason:why.join('；')});e.records=e.records.slice(-100);e.applications=e.applications.filter(x=>x!==a);}}
function validate(s){const e=s.establishment;if(!e||!e.quotas||!Number.isInteger(e.officeLevel)||e.officeLevel<0||e.officeLevel>3||!Number.isInteger(e.upgradeDue)||e.upgradeDue<0||e.upgradeDue&&e.upgradeDue<=s.month)throw Error('机构编制台账不正确。');for(const k of Object.keys(ROLES))if(!Number.isInteger(e.quotas[k])||e.quotas[k]<0||e.quotas[k]>1000||used(s,k)>e.quotas[k])throw Error('分类编制或占编数据不正确。');if(!Array.isArray(e.applications)||e.applications.length>3||new Set(e.applications.map(a=>a.role)).size!==e.applications.length||e.applications.some(a=>!ROLES[a.role]||!Number.isInteger(a.amount)||a.amount<1||a.amount>10||!Number.isInteger(a.due)||a.due<=s.month||!Number.isInteger(a.submitted)||a.submitted<0||a.submitted>s.month))throw Error('增编申请不正确。');if(!Array.isArray(e.records)||e.records.length>100||e.records.some(a=>!ROLES[a.role]||!Number.isInteger(a.amount)||a.amount<1||a.amount>10||!Number.isInteger(a.finished)||a.finished>s.month||typeof a.approved!=='boolean'||typeof a.reason!=='string'))throw Error('编制审批记录不正确。');}
const api={ROLES,init,used,officeCapacity,ceilings,financial,reasons,request,upgrade,tick,validate};if(typeof module!=='undefined')module.exports=api;else root.Staffing=api;
})(globalThis);
