const {test}=require('node:test'),assert=require('node:assert/strict'),G=require('./engine');
test('建设连接约束、扣款与两月工期',()=>{let s=G.initial();assert.ok(G.build(s,0,'school'));assert.equal(s.cash,1500);assert.equal(G.build(s,6*18+10,'school'),null);assert.equal(s.cash,1320);s.staff.teachers=6;assert.equal(G.metrics(s).education,0);G.next(s);assert.equal(G.metrics(s).education,0);G.next(s);assert.ok(G.metrics(s).education>0);});
test('断路会停止服务',()=>{let s=G.initial();G.build(s,6*18+1,'school');s.staff.teachers=6;G.next(s);G.next(s);assert.ok(G.metrics(s).education>0);G.build(s,7*18+1,'demolish');assert.equal(G.metrics(s).education,0);});
test('桥梁拆除恢复水面且桥价三倍',()=>{let s=G.initial(),i=14;let cash=s.cash;G.build(s,i,'road');assert.equal(s.cash,cash-24);G.build(s,i,'demolish');assert.equal(s.cells[i].type,'river');assert.ok(G.build(s,i,'home'));});
test('禁止直接发债，旧债本金与准备金偿还守恒',()=>{let s=G.initial();assert.ok(G.finance(s,'borrow'));assert.equal(s.cash,1500);s.debt=300;assert.equal(G.metrics(s).interest,300*.065/12);s.reserve=80;G.finance(s,'repay');assert.equal(s.cash,1380);assert.equal(s.debt,100);assert.equal(s.reserve,0);});
test('资金优先工资运转，连续缺口结束',()=>{let s=G.initial();s.cash=0;s.staff.admin=90;s.staff.teachers=20;G.next(s);assert.equal(s.last.paid.welfare,0);assert.ok(s.last.paid.wages>0);assert.equal(s.cash,0);G.next(s);G.next(s);assert.ok(s.ended);assert.equal(s.month,3);});
test('事件不能重复处理，逾期有后果，审计延迟触发',()=>{let s=G.initial();s.events=[{id:1,kind:3,deadline:3}];G.resolve(s,1,2);let rep=s.reputation;assert.ok(G.resolve(s,1,2));for(let i=0;i<6;i++)G.next(s);assert.equal(s.reputation,rep-12);assert.ok(s.log.some(l=>l.text.includes('审计追责')));s=G.initial();s.events=[{id:1,kind:0,deadline:1}];G.next(s);assert.equal(s.events.length,0);assert.ok(s.log.some(l=>l.text.includes('逾期')));});
test('存档复原后结算完全可重现',()=>{let s=G.initial();for(let i=0;i<8;i++)G.next(s);let copy=G.validate(JSON.parse(JSON.stringify(s)));G.next(s);G.next(copy);assert.deepEqual(copy,s);assert.throws(()=>G.validate({version:1}));let bad=G.initial();bad.events=[{kind:999,id:1,deadline:2}];assert.throws(()=>G.validate(bad));});
test('五年继续运行，35年结局后禁止建设与结算',()=>{let s=G.initial();for(let i=0;i<G.Career.LIMIT;i++){G.next(s);for(const e of [...s.events])G.resolve(s,e.id,1);if(s.month===60){assert.equal(s.ended,null);assert.equal(s.career.terms.length,1);}}assert.equal(s.month,420);assert.equal(s.reviews.length,35);assert.ok(s.ended);let snapshot=JSON.stringify(s);assert.ok(G.next(s));assert.ok(G.build(s,0,'road'));assert.equal(JSON.stringify(s),snapshot);});
test('固定税制与行政服务分离',()=>{let s=G.initial(),income=G.metrics(s).tax;s.staff.admin=0;s.policy.tax=18;assert.equal(G.metrics(s).tax,income);assert.equal(G.metrics(s).adminEfficiency,0);});
test('建设受预算和三个月基本支出预留限制',()=>{let s=G.initial();s.budget.limit=10;assert.ok(G.build(s,118,'school'));assert.equal(s.cash,1500);s.budget.limit=900;s.cash=200;assert.ok(G.build(s,118,'school'));assert.equal(s.cells[118].type,'empty');});
test('招录延迟到岗，待到岗占编，调出期间继续发薪',()=>{let s=G.initial();assert.equal(G.hire(s,'teachers',1),null);assert.equal(s.staff.teachers,0);assert.equal(s.cash,1492);G.next(s);assert.equal(s.staff.teachers,0);G.next(s);assert.equal(s.staff.teachers,1);G.hire(s,'teachers',-1);assert.ok(G.hire(s,'teachers',-1));let wage=G.metrics(s).wages;G.next(s);assert.equal(G.metrics(s).wages,wage);G.next(s);G.next(s);assert.equal(s.staff.teachers,0);s.staff.admin=20;s.staff.teachers=0;s.staff.doctors=0;s.pop=1450;assert.equal(G.hire(s,'teachers',1),null);});
test('专项申报限用途、无即时现金、按工程支付',()=>{let s=G.initial();assert.ok(G.build(s,118,'school','special'));assert.equal(G.build(s,118,'water','special'),null);assert.equal(s.cash,1500);assert.ok(G.build(s,118,'water','special'));G.next(s);assert.equal(s.loans.length,0);G.next(s);assert.equal(s.specialCash,190);assert.equal(s.loans[0].balance,190);assert.equal(s.cells[118].wait,2);assert.equal(s.loans[0].due,38);assert.ok(G.build(s,118,'demolish'));G.next(s);assert.equal(s.specialCash,95);G.next(s);assert.equal(s.specialCash,0);assert.equal(s.cells[118].wait,0);assert.ok(G.metrics(s).projectRevenue>0);G.validate(JSON.parse(JSON.stringify(s)));});
test('专款不能填补基本支出，欠款继续留账',()=>{let s=G.initial();G.build(s,118,'water','special');G.next(s);G.next(s);s.cash=0;s.staff.admin=90;s.staff.teachers=20;G.next(s);assert.equal(s.specialCash,95);assert.equal(s.last.paid.welfare,0);assert.ok(s.payables>0);assert.ok(s.last.basicGap>0);});
test('审批时重新评估，不合格申报退回且不形成债务',()=>{let s=G.initial();G.build(s,118,'water','special');s.debt=10000;G.next(s);G.next(s);assert.equal(s.projects.length,0);assert.equal(s.loans.length,0);assert.equal(s.specialCash,0);assert.equal(s.cells[118].type,'empty');});
test('专项债按期还本，利息与本金从项目资金扣减',()=>{let s=G.initial();s.loans=[{cell:118,balance:190,due:1}];s.projectReserve=200;G.next(s);assert.equal(s.loans[0].balance,0);assert.ok(Math.abs(s.projectReserve-(200-190-190*.028/12))<1e-8);assert.equal(s.last.paid.principal,0);});
test('专项到期不足部分不会消失',()=>{let s=G.initial();s.loans=[{cell:118,balance:1000,due:1}];s.cash=0;G.next(s);assert.ok(s.loans[0].balance>0);assert.ok(G.metrics(s).specialPrincipal>0);});
test('旧存档迁移保留城市现金和旧债，坏台账拒绝导入',()=>{let s=G.initial();s.version=1;s.cash=1234;s.debt=250;s.policy.tax=18;for(const k of ['projects','loans','budget','recruitment','payables','goodYears','specialCash','projectReserve','career'])delete s[k];let restored=G.validate(s);assert.equal(restored.version,7);assert.equal(restored.cash,1234);assert.equal(restored.debt,250);assert.equal(restored.policy.tax,10);restored.specialCash=100;assert.throws(()=>G.validate(restored));});

